### ISSUE TITLE
Tasks: Carry on next month

### ISSUE THREAD

**Issue by Llediarth** [roxlukas/lmeve#19]
It would be great if created tasks could be carried on in the next month.

Current situation: Tasks can be created either as one time tasks or repetitive tasks. Both ways are quite suboptimal when having a lot of tasks withhin a corp.

Issues: Mats brought to arrays at the beginning of tasks > left overs at the end of the month > accumulate over month > hazzle to sort out

Solution: when creating tasks, it should be possible to mark them not only as one time task or repetitive task but as well as "take over to next month". Even further, this should be default as also with repetitive tasks a lot of mats and especially t2-copies get stockpiled. Tasks should not reset at the beginning of a new month. At least an option to set this would be nice :-)

**Comment by roxlukas** [comment]
Well, this isn't so easy as it sounds. Here's why:

  * Imagine a tape that goes back to past, to the day where the corporation was created and extends to present time - this is basically your whole IndustryJobs table.
  * To show progress on a task, you need to know how many items to build (that's in the task table) and how many have already been made - this is a SQL COUNT aggregate query over the IndustryJobs table.
  * A task is also a specific item (typeID) made by specific character (installerID) - so these will be the criteria for our aggregate query.
  * If you don't specify start and end date, you will get a count of all items made by this character since the beginning of coroporation until present time (whole tape so to speak). And as time passes, and more items are built, this number will keep growing.

So a COUNT aggregate query needs borders. Months are natural borders, and so are weeks used by Aideron Robotics tool.

What we could do, because tasks have a start date, is use this start date as the first border. Unfortunately we still need something as the end border.

**Comment by Llediarth** [comment]
Can we then at least use as end border for non-recurring task: following month?

We just need it to keep the non-recurring tasks alive a few days into the following month. No need to keep the end border for ever into eternity. Two month instead of one should be totally sufficient.

**Comment by roxlukas** [comment]
In my opinion "until it's finished" would be more logical option than "two months". What do you think?

**Comment by Llediarth** [comment]
But isnt that excactly the issue we might run into? What happens if someone gets afk or for what ever reason doesnt finish the job?

**Comment by roxlukas** [comment]
The task will keep showing until it's a) completed or b) deleted
What I want to avoid is for the task to show up ininitely without any way to complete.

**Comment by roxlukas** [comment]
Added in ca4d948
