### ISSUE TITLE
Enhancement: Global Tasks

### ISSUE THREAD

**Issue by clstb** [roxlukas/lmeve#36]
Add tasks that are available for everyone. The first that are seeing the task can execute it first. So teamleaders dont have to wait for individual producers and therefore have a better flow in completing projects. Also teamleaders dont have to mess with what each character can produce.

EDIT:
Only add that global task to characters that are in a specific group.

**Comment by roxlukas** [comment]
**IMPORTANT INFORMATION** My dev laptop has recently suffered a hardware failure*, and because of very tight budget I won't be able to replace it anytime soon. Due to the above fixes will be delayed, but rest assured I haven't given up on LMeve yet.

*) Most likely GPU or Northbridge went up in smoke

**Comment by roxlukas** [comment]
Please let me know if this enhancement is still required?

**Comment by clstb** [comment]
Not playing eve anymore, tho i still think it's a good feature.

**Comment by dstevens79** [comment]
id say the ability to generate global tasks and assign yourself with a dropdown to one of those global tasks would b a nice feature
