### ISSUE TITLE
Market Tab, Buy Orders Incorrect Column Heading

### ISSUE THREAD

**Issue by Wildweasel24** [roxlukas/lmeve#39]
For Buy Orders, volume column should be titled 'Volume Bought' not 'Volume Sold'

**Comment by roxlukas** [comment]
Haha, sure, will fix :-D

**Comment by roxlukas** [comment]
**IMPORTANT INFORMATION** My dev laptop has recently suffered a hardware failure*, and because of very tight budget I won't be able to replace it anytime soon. Due to the above fixes will be delayed, but rest assured I haven't given up on LMeve yet.

*) Most likely GPU or Northbridge went up in smoke
