### ISSUE TITLE
CREST Changes

### ISSUE THREAD

**Issue by Wildweasel24** [roxlukas/lmeve#40]
In case you didn't catch the announcement.

https://developers.eveonline.com/blog/article/crest-renovations-2016-06

**Comment by roxlukas** [comment]
Thanks for the heads up, I have indeed missed this one. This change does
not have much effect on LMeve. CREST endpoints which I use weren't changed.

One change will be required in Database - CREST typeID link.

**Comment by roxlukas** [comment]
**IMPORTANT INFORMATION** My dev laptop has recently suffered a hardware failure*, and because of very tight budget I won't be able to replace it anytime soon. Due to the above fixes will be delayed, but rest assured I haven't given up on LMeve yet.

*) Most likely GPU or Northbridge went up in smoke

**Comment by jjwedemyer** [comment]
what would be the change? maybe there's a way someone else could fix it!

**Comment by roxlukas** [comment]
It does not affect the inner workings of LMeve. It's only a display issue.
When you go to Database and open a specific item, in the bottom left column
there are API links pointing to that item. Only this link is broken for
CREST.

The change is very simple.
