### ISSUE TITLE
Copy tasks

### ISSUE THREAD

**Issue by clstb** [roxlukas/lmeve#41]
Add how much runs every copy should have.

**Comment by roxlukas** [comment]
**IMPORTANT INFORMATION** My dev laptop has recently suffered a hardware failure*, and because of very tight budget I won't be able to replace it anytime soon. Due to the above fixes will be delayed, but rest assured I haven't given up on LMeve yet.

*) Most likely GPU or Northbridge went up in smoke

**Comment by roxlukas** [comment]
Please let me know if this enhancement is still required?

**Comment by clstb** [comment]
Not playing eve anymore, tho i still think it's a good feature.
