### ISSUE TITLE
Best Practices for Updating

### ISSUE THREAD

**Issue by wtdewilligen** [roxlukas/lmeve#43]
Just wanted to see if there was a preferred way of upgrading the lmeve install. I thought about just dropping it in and going but wasn't sure if there was a good way of doing things. 

Thanks!

**Comment by roxlukas** [comment]
Hi,

LMeve consists of two parts: PHP files and DB schema. Since both evolve, both must be updated. 
PHP files are easy to update - simply copy the new version over the old one.

To ease the burden of database updates I've created a file called "dbcatalog.php" which tries to detect if db tables need an update and updates them automatically **on first admin login**. This mechanism was introduced in May 2016, so if you've installed after this date, simply copy over PHP files. If you have an older LMeve version, go to data directory and import all "schema delta" sql files between your previous version and 0.1.55, which was the last one before introducing dbcatalog.
